us_funds_dbt:
  outputs:
    dev:
      type: duckdb
      path: '/us-funds-performance/us-funds-project.db'
      threads: 4

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
